### ISSUE TITLE
FiveTran Data Extractor

### ISSUE THREAD

**Issue by angelini** [gadget-inc/dateilager#33]
This issue will be a quick design doc on how to implement the custom FiveTran data extractor for DateiLager.

https://fivetran.com/docs/functions
https://fivetran.com/docs/functions/google-cloud-functions

## Initial goals:
- We want decompressed file contents for each app
- Instead of maintaining the full history of each app's filesystem, we'll extract the current state of the filesystem
    - Fivetran supports appending and deleting keys and DL can easily figure out what has changed since the last sync
- Keep a denormalized copy of every file to make it very easy to query
    - Since we'll just be keeping the latest version of the FS we could keep the content of each file denormalized for each app

## Output Table Schema:

App Filesystems:
- project_id (equivalent to environment ID)
- path
- start_version (no need for stop_version as it will always be `null`)
- mode
- size
- content

The primary key for this table will be: `[project_id, path]`

## State

The custom Fivetran functions work with the concept of a `state` that is passed to each call to the function. 

Normally you would use something like a `last_synched` timestamp, but at the moment we do not keep timestamp metadata in DL - this will be coming in a new version.

So for now I think the simplest state we could use is:

```
{
  '<project_id>: <latest_version>,
  ...
}
```

For each project (1 per environment) we save an integer which is the latest version we extracted.

## Increment

When the function is run we need to sync new data based on the incoming state and build a new output state.

There are two possible new kinds of data: new projects IDs that are not in the state object & projects with greater `latest_versions` than what we have in the state object.

An increment will run N updates, where an update is either syncing a new project or updating an existing project.

To generate the update for a project we simply run the DL query: get all file updates from version <existing_version_in_the_state_object> to <latest_version>.

Deleted files are added to the Fivetran `delete` key and new files are added to the Fivetran `insert` key.

If we ran N updates we emit: `hasMore= true`, which will cause the sync function to run again, otherwise we emit `hasMore = false`.

## Auth

This will require an Admin DL token, which we can feed to the function via Fivetran's `secrets` feature.

/cc @airhorns @scott-rc @infiton

**Comment by scott-rc** [comment]
cc @thegedge too since we were talking about this yesterday 😄

**Comment by infiton** [comment]
I have a fivetran connector using this technique for orb for reference:

- connector: https://fivetran.com/dashboard/connectors/felony_betrothed/status?groupId=inconvenience_incisors&service=google_cloud_function
- cloud function: https://console.cloud.google.com/functions/details/us-central1/fivetran-orb-extractor?env=gen1&authuser=1&project=gadget-core-production

One issue I have come across with cloud function extractors is that fivetran doesn't yet support the soft delete functionality that other connectors have. They told me they are working on it for early 2023 though

**Comment by scott-rc** [comment]
This has been implemented 🎉
